### ISSUE TITLE
fluctus

### ISSUE THREAD

**Issue by rl1234567890** [Alatius/latin-macronizer#19]
Macronizer gives flūctus. I believe it should be fluctus, since the u in [fluō](https://logeion.uchicago.edu/fluo)  is short. Thanks!

**Comment by majadirks** [comment]
On the other hand, _Familia Romana_ consistently marks that vowel as long, agreeing with Macronizer. I'm curious what the correct answer is!

**Comment by increpare** [comment]
The following dictionaries all give it with short u, fwiw:

Charlton T. Lewis, Charles Short - A Latin Dictionary
http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.04.0059:entry=fluctus

Charlton T. Lewis - An Elementary Latin Dictionary
http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.04.0060:entry=fluctus

Gaffiot, Félix - Dictionnaire illustré Latin-Français
http://micmap.org/dicfro/search/gaffiot/fluctus

**Comment by jrhaneydata** [comment]
Most of the dictionaries on Logeion (https://logeion.uchicago.edu/fluctus) mark it as flūctus, and the the long u accords with Lachmann's Law.

https://en.wikipedia.org/wiki/Lachmann%27s_law

**Comment by Alatius** [comment]
When a syllable is long by position (as in this case), the fact that some dictionaries do not mark the vowel with a macron should not necessarily be interpreted as an express statement that the vowel is short (and vice versa). Traditionally, the so  called "hidden quantity" of the vowel has not really been the focus of lexicographers, since it has little practical consequences (such as in terms of scansion). Thus, some dictionaries are more reliable than others. When in doubt, I have begun to rely on the Latin-Dutch dictionary available on Logeion. In this case, it marks it "flūctus", in accord with the arguments presented here.
