### ISSUE TITLE
Error: Something went wrong with the tagging.

### ISSUE THREAD

**Issue by rl1234567890** [Alatius/latin-macronizer#7]
Hi,

I was trying to upgrade my local installation.   python macronize.py --test worked fine, but when I copied everything to /usr/local and run it on "Rosa" I get

Error: Something went wrong with the tagging.

Any idea why?

**Comment by Alatius** [comment]
Hi! First, please excuse the very uninformative error message you got! I have to do something about that. It may be that the macronizer failed to call the tagger. Have you edited the constant "RFTAGGERDIR" at the beginning of the file "macronizer.py"? It should point to the directory where the program "rft-annotate" resides. Don't forget the final "/" (e.g., it should be '/usr/local/bin/' rather than '/usr/local/bin')!

**Comment by Alatius** [comment]
I think it is also possible to get that error message if you haven't edited "MACRONIZERLIB" in "macronize.py". It should be the full path to where the other file "macronizer.py" resides, not only the relative path ".".

**Comment by rl1234567890** [comment]
The MACRONIZERLIB  was the problem, thanks!
