### ISSUE TITLE
Problem with latest release

### ISSUE THREAD

**Issue by rl1234567890** [Alatius/latin-macronizer#8]
Hi,

I made sure I have the latest version

After going through 
./train-rftagger.sh
python macronize.py --initialize
python macronize.py --test
Traceback (most recent call last):
  File "macronize.py", line 314, in <module>
    macronizer.settext(texttomacronize)
  File "/Users/lionel/latin-macronizer/macronizer.py", line 1054, in settext
    self.tokenization.addlemmas(self.wordlist)
  File "/Users/lionel/latin-macronizer/macronizer.py", line 501, in addlemmas
    from lemmas import lemma_frequency, word_lemma_freq, wordform_to_corpus_lemmas
ImportError: No module named lemmas

Any idea? In general, what is the right procedure for an update? Thanks!

**Comment by Alatius** [comment]
When you run the script "train-rftagger.sh", the first thing it does is calling "python extractlexicon.py", which (as of the latest commit) should generate the file "lemmas.py", but what I guess is happening is that you get an error message at that stage. There's obviously a flaw in the script, because it goes on with the next command, training the tagger, despite that error, and so the error message is hidden behind all the output from the tagger training. Please run "python extractlexicon.py", and report the output you get.

I am currently making some structural edits to the code, so the installation/update procedure may change. Actually, as far as I know, the recent commits shouldn't actually change the quality of the macronization, so if your local installation is working well, there is no major reason to update at this stage.

**Comment by rl1234567890** [comment]
Oops! I forgot about treebank_data. It seems to work now. Sorry and thanks!
